name: Factory - PR Validation

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'images/**'
      - '.github/workflows/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  matrix-build-and-audit:
    name: Build & Audit (${{ matrix.image.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: static
            path: images/static
            context: ./images/static
          - name: core-runtime
            path: images/core-runtime
            context: ./images/core-runtime

    steps:
      - name: Checkout Source
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Lint Containerfile (Hadolint)
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: ${{ matrix.image.path }}/Containerfile

      - name: Build OCI Image (Buildah)
        id: build-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: hardened-${{ matrix.image.name }}
          tags: pr-${{ github.event.pull_request.number }}
          context: ${{ matrix.image.context }}
          containerfiles: ${{ matrix.image.path }}/Containerfile
          oci: true

      - name: Vulnerability Audit with Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: 'hardened-${{ matrix.image.name }}:pr-${{ github.event.pull_request.number }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
