name: Factory - PR Validation

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'images/**'
      - '.github/workflows/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  matrix-build-and-audit:
    name: Build & Audit (${{ matrix.image.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: static
            path: images/static
            context: ./images/static
          - name: core-runtime
            path: images/core-runtime
            context: ./images/core-runtime

    steps:
      - name: Checkout Source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint Containerfile (Hadolint)
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: ${{ matrix.image.path }}/Containerfile

      - name: Build OCI Image (Buildah)
        id: build-image
        uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
        with:
          image: hardened-${{ matrix.image.name }}
          tags: pr-${{ github.event.pull_request.number }}
          context: ${{ matrix.image.context }}
          containerfiles: ${{ matrix.image.path }}/Containerfile
          oci: true

      - name: Export Image for Trivy
        env:
          IMAGE: ${{ steps.build-image.outputs.image-with-tag }}
        run: buildah push "$IMAGE" "docker-archive:$RUNNER_TEMP/image.tar"

      - name: Vulnerability Audit with Trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          input: '${{ runner.temp }}/image.tar'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
